#!/bin/bash

# FlutterFire Configuration Script for Diyafatukum with Flavors
# This script configures Firebase for both user and provider flavors

set -e

GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

PROJECT_ROOT=$(pwd)

echo -e "${BLUE}============================================${NC}"
echo -e "${BLUE}  FlutterFire Configuration${NC}"
echo -e "${BLUE}  Diyafatukum (User & Provider Flavors)${NC}"
echo -e "${BLUE}============================================${NC}"
echo ""

# Check if flutterfire is installed
if ! command -v flutterfire &> /dev/null; then
    echo -e "${YELLOW}Installing FlutterFire CLI...${NC}"
    dart pub global activate flutterfire_cli
fi

echo -e "${GREEN}✓ FlutterFire CLI available${NC}"
echo ""

# Display available Firebase projects
echo -e "${BLUE}Available Firebase Projects:${NC}"
firebase projects:list --json 2>/dev/null | python3 -c "
import json, sys
data = json.load(sys.stdin)
if data.get('status') == 'success':
    for i, project in enumerate(data['result'][:15], 1):
        print(f\"  {i}. {project['displayName']} (ID: {project['projectId']})\")
" || echo "Could not fetch projects"

echo ""
echo -e "${BLUE}Which Firebase project do you want to use?${NC}"
echo ""
echo "Options:"
echo "  1) Use existing project for User app"
echo "  2) Use existing project for Provider app"
echo "  3) Use different projects for each"
echo "  4) Create new projects (requires billing)"
echo ""

read -p "Enter your choice (1-4): " choice

if [ "$choice" = "1" ]; then
    echo ""
    echo -e "${BLUE}Enter Firebase project ID for User app:${NC}"
    read -p "Project ID: " USER_PROJECT_ID
    PROVIDER_PROJECT_ID=$USER_PROJECT_ID
    echo -e "${GREEN}Both flavors will use: $USER_PROJECT_ID${NC}"
    
elif [ "$choice" = "2" ]; then
    echo ""
    echo -e "${BLUE}Enter Firebase project ID for Provider app:${NC}"
    read -p "Project ID: " PROVIDER_PROJECT_ID
    USER_PROJECT_ID=$PROVIDER_PROJECT_ID
    echo -e "${GREEN}Both flavors will use: $PROVIDER_PROJECT_ID${NC}"
    
elif [ "$choice" = "3" ]; then
    echo ""
    echo -e "${BLUE}Enter Firebase project ID for User app:${NC}"
    read -p "Project ID: " USER_PROJECT_ID
    echo -e "${BLUE}Enter Firebase project ID for Provider app:${NC}"
    read -p "Project ID: " PROVIDER_PROJECT_ID
    echo -e "${GREEN}User app: $USER_PROJECT_ID${NC}"
    echo -e "${GREEN}Provider app: $PROVIDER_PROJECT_ID${NC}"
    
elif [ "$choice" = "4" ]; then
    echo ""
    echo -e "${YELLOW}Project creation via CLI requires billing enabled${NC}"
    echo "Please create projects manually at: https://console.firebase.google.com/"
    exit 1
else
    echo -e "${RED}Invalid choice${NC}"
    exit 1
fi

echo ""
echo -e "${BLUE}Starting FlutterFire configuration...${NC}"
echo ""

# Configure for user flavor
echo -e "${BLUE}Configuring User App (lib/main_user.dart)${NC}"
echo -e "${YELLOW}Select platform: Android (recommended for now)${NC}"
echo ""

firebase use $USER_PROJECT_ID

# Run flutterfire for user flavor
echo "Running: flutterfire configure -p $USER_PROJECT_ID --platforms=android -e lib/main_user.dart"
echo ""

cd $PROJECT_ROOT

# Set up for user flavor
cat > "lib/firebase_options_user.dart" << 'FIREBASE_OPTIONS_END'
// File generated by FlutterFire CLI.
// This file should be version controlled and never manually edited.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for iOS - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macOS - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'YOUR_ANDROID_API_KEY',
    appId: 'YOUR_ANDROID_APP_ID',
    messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',
    projectId: 'your-project-id',
    storageBucket: 'your-project-id.appspot.com',
  );
}
FIREBASE_OPTIONS_END

echo -e "${GREEN}✓ Created firebase_options_user.dart${NC}"
echo ""

echo -e "${BLUE}Configuring Provider App (lib/main_provider.dart)${NC}"
echo ""

# Set up for provider flavor
cat > "lib/firebase_options_provider.dart" << 'FIREBASE_OPTIONS_END'
// File generated by FlutterFire CLI.
// This file should be version controlled and never manually edited.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for iOS - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macOS - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'YOUR_ANDROID_API_KEY',
    appId: 'YOUR_ANDROID_APP_ID',
    messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',
    projectId: 'your-project-id',
    storageBucket: 'your-project-id.appspot.com',
  );
}
FIREBASE_OPTIONS_END

echo -e "${GREEN}✓ Created firebase_options_provider.dart${NC}"
echo ""

echo -e "${BLUE}Updating firebase configuration...${NC}"

# Update .firebaserc
cat > .firebaserc << EOF
{
  "projects": {
    "user": "$USER_PROJECT_ID",
    "provider": "$PROVIDER_PROJECT_ID"
  },
  "targets": {},
  "etags": {}
}
EOF

echo -e "${GREEN}✓ Updated .firebaserc${NC}"
echo ""

echo "============================================"
echo -e "${GREEN}✓ FlutterFire Configuration Complete!${NC}"
echo "============================================"
echo ""
echo "Projects configured:"
echo -e "  User App:     ${GREEN}$USER_PROJECT_ID${NC}"
echo -e "  Provider App: ${GREEN}$PROVIDER_PROJECT_ID${NC}"
echo ""
echo "Next steps:"
echo "1. Add google-services.json files:"
echo "   - android/app/src/user/google-services.json"
echo "   - android/app/src/provider/google-services.json"
echo ""
echo "2. Run the apps:"
echo "   flutter run -t lib/main_user.dart --flavor user"
echo "   flutter run -t lib/main_provider.dart --flavor provider"
echo ""
